# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_apicase_apilist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apilist',
            old_name='ApiName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='apilist',
            old_name='ApiNotes',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='apilist',
            old_name='ApiUrl',
            new_name='url',
        ),
        migrations.AlterModelTable(
            name='apilist',
            table='apilist',
        ),
    ]
