# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 03:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160523_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apicase',
            old_name='CaseName',
            new_name='apiname',
        ),
        migrations.RenameField(
            model_name='apicase',
            old_name='ApiUrl',
            new_name='apiurl',
        ),
        migrations.RenameField(
            model_name='apicase',
            old_name='CaseCheck',
            new_name='check',
        ),
        migrations.RenameField(
            model_name='apicase',
            old_name='CaseData',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='apicase',
            old_name='CaseMothed',
            new_name='mothed',
        ),
        migrations.RenameField(
            model_name='apicase',
            old_name='casenotes',
            new_name='notes',
        ),
        migrations.AlterModelTable(
            name='apicase',
            table='apicase',
        ),
    ]
