# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160524_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicase',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
