# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_apicase_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('casej', models.TextField()),
                ('notes', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'project',
            },
        ),
    ]
