# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_result_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
